import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import "../css/globals.css";
import Provider from "./Provider";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" dir="ltr">
            <body className="font-[roboto] capitalize h-screen flex items-center justify-center">
                <Provider>
                    {children}
                    <ReactQueryDevtools />
                </Provider>
            </body>
        </html>
    );
}
